// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $create_contact from "./routes/create-contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $submitform from "./routes/submitform.tsx";
import * as $ChatArea from "./islands/ChatArea.tsx";
import * as $ContactList from "./islands/ContactList.tsx";
import * as $ContactSidebar from "./islands/ContactSidebar.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $MessageInput from "./islands/MessageInput.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/create-contact.tsx": $create_contact,
    "./routes/index.tsx": $index,
    "./routes/submitform.tsx": $submitform,
  },
  islands: {
    "./islands/ChatArea.tsx": $ChatArea,
    "./islands/ContactList.tsx": $ContactList,
    "./islands/ContactSidebar.tsx": $ContactSidebar,
    "./islands/Form.tsx": $Form,
    "./islands/MessageInput.tsx": $MessageInput,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
